Objetivo: Probar la lógica de limpieza de tiempos negativos y validación de outliers usando .mask() antes de pasarlo al script maestro.
Autor: José Arturo Pérez Falcón
Fecha: Febrero 2026

In [2]:
import pandas as pd

df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Silver_PBI_Final.parquet')
df.info()
print(df.describe())
display(df)

""" # 1. Le decimos a Pandas que repita cada fila el número de veces que diga 'Total_Ordenes'
# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente
df_prueba = df.loc[df.index.repeat(df['Total_Ordenes'])]

# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación
display(df_prueba.groupby('Clasificacion')['SLA Resolucion Min'].median())
display(df) """

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\josperez\\Documents\\A-DataStack\\01-Proyectos\\01-Data_PipelinesFibex\\02_Data_Lake\\gold_data\\Silver_PBI_Final.parquet'

In [1]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')

display(df)

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,Clasificacion,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden
0,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-10 10:36:00,2026-03-10 11:33:00,NaT,2026-03-10,NaT,1,0,...,MESA DE CONTROL,1142,008612,ACTIVO,IMPRESA,<NA>,JGMEZA,JYAMARTE,<NA>,CAIDAS SEGUIDAS DE INTERNET
1,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-31 13:34:00,2026-03-31 14:08:00,NaT,2026-03-31,NaT,1,0,...,MESA DE CONTROL,1213,010074,ACTIVO,IMPRESA,<NA>,APICONEXVE,DFUENTES,<NA>,SIN INTERNET
2,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 14:12:00,2026-04-01 15:20:00,NaT,2026-04-01,NaT,1,0,...,OPERACIONES,MI1332,MI206221,ACTIVO,IMPRESA,<NA>,YATOVAR,VGAMEZ,<NA>,FALLA LOS
3,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 16:33:00,2026-04-01 16:35:00,NaT,2026-04-01,NaT,1,0,...,MESA DE CONTROL,MI14186,MI206250,ACTIVO,IMPRESA,<NA>,KCHACON,KCHACON,<NA>,SIN INTERNET
4,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-02 10:28:00,2026-04-02 10:29:00,NaT,2026-04-02,NaT,1,0,...,MESA DE CONTROL,MI13664,MI206305,ACTIVO,IMPRESA,<NA>,ADRROJAS,ADRROJAS,<NA>,CAIDAS SEGUIDAS DE INTERNET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195923,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-11 10:25:00,2026-04-12 18:27:00,2026-04-15 23:48:00,2026-04-11,2026-04-15,1,0,...,MESA DE CONTROL,V4004,V584763,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,NSANTANA,REEMPALME DE HILO,SIN INTERNET
195924,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-15 09:24:00,2026-04-15 23:48:00,2026-04-15 23:49:00,2026-04-15,2026-04-15,1,1,...,MESA DE CONTROL,LCH37147,LCH524185,ACTIVO,FINALIZADA,ANTHGONZALEZ,SMARQUEZ,ANTHGONZALEZ,CONFIGURACION DE EQUIPO,SIN INTERNET
195925,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-13 09:04:00,2026-04-13 17:27:00,2026-04-15 23:50:00,2026-04-13,2026-04-15,1,0,...,MESA DE CONTROL,H5391,V609829,ACTIVO,FINALIZADA,ANQUINTERO,MSANTANA,FRPARRA,REEMPALME DE HILO,SIN INTERNET
195926,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-12 16:45:00,2026-04-13 13:49:00,2026-04-15 23:51:00,2026-04-12,2026-04-15,1,0,...,MESA DE CONTROL,V77733,V591199,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,FLEAL,REEMPALME DE HILO,SIN INTERNET
195927,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-15 09:27:00,2026-04-15 23:56:00,2026-04-15 23:58:00,2026-04-15,2026-04-15,1,1,...,MESA DE CONTROL,LCH47358,LCH524208,ACTIVO,FINALIZADA,ANTHGONZALEZ,BLCARRILO,ANTHGONZALEZ,FALLA DE DFS,USUARIO CLAVE ONT

In [5]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet')
df.groupby(['Quincena Evaluada','Clasificacion']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()
df.pivot_table(index='Quincena Evaluada', columns='Clasificacion', values='SLA Resolucion Min', aggfunc='median')

Clasificacion      MESA DE CONTROL    NOC  OPERACIONES
Quincena Evaluada
ABR 2026 Q1                  984.0  244.0       1550.0
AGO 2025 Q1                 1131.0   90.0       5838.0
AGO 2025 Q2                 1249.0  163.0       5391.0
DIC 2025 Q1                  172.0   76.0       1501.0
DIC 2025 Q2                  154.0   82.0       1321.0
ENE 2026 Q1                  145.0  102.0       1145.0
ENE 2026 Q2                  219.0  103.0       1436.0
FEB 2026 Q1                  198.0  102.0       1505.0
FEB 2026 Q2                  456.0  109.0       1647.0
MAR 2026 Q1                  294.0  100.0       1609.0
MAR 2026 Q2                  273.0   85.0       1546.0
NOV 2025 Q1                  210.0   55.0       2771.0
NOV 2025 Q2                  454.0   49.0       1720.0
OCT 2025 Q1                  259.0  113.0       2593.0
OCT 2025 Q2                  237.0  112.0       2584.0
SEP 2025 Q1                  938.0  133.0       2973.0
SEP 2025 Q2                  545.5  137.0       1863.0

In [ ]:
import pandas as pd
df = pd.read_excel(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet',engine = 'calamine')

In [4]:
import pandas as pd
idf = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\IDF_Gold.parquet')
franq = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Stock_Abonados_Gold_Resumen.parquet')
display(idf)
display(franq)

,Quincena Evaluada,Franquicia,Fecha Apertura Date,Fecha Cierre Date,Total_Fallas
0,ABR 2026 Q1,FIBER HOGAR - MATURIN,2026-03-17,2026-04-06,1
1,ABR 2026 Q1,FIBER HOGAR - MATURIN,2026-03-31,2026-04-01,5
2,ABR 2026 Q1,FIBER HOGAR - MATURIN,2026-04-01,2026-04-01,3
3,ABR 2026 Q1,FIBER HOGAR - MATURIN,2026-04-01,2026-04-02,2
4,ABR 2026 Q1,FIBER HOGAR - MATURIN,2026-04-02,2026-04-02,2
...,...,...,...,...,...
23893,SEP 2025 Q2,FIBEX YARITAGUA,2025-09-26,2025-09-29,1
23894,SEP 2025 Q2,FIBEX YARITAGUA,2025-09-27,2025-09-29,2
23895,SEP 2025 Q2,FIBEX YARITAGUA,2025-09-29,2025-09-29,1
23896,SEP 2025 Q2,FIBEX YARITAGUA,2025-09-29,2025-09-30,2
23897,SEP 2025 Q2,FIBEX YARITAGUA,2025-09-30,2025-09-30,1

    Quincena Evaluada              Franquicia  Total_Abonados Fecha_Corte
0         DIC 2025 Q1           FIBEX CARACAS           27568  2025-12-15
1         DIC 2025 Q1            FIBEX ARAGUA           42109  2025-12-15
2         DIC 2025 Q1     FIBEX PUNTA DE MATA             674  2025-12-15
3         DIC 2025 Q1           FIBEX BARINAS             747  2025-12-15
4         NOV 2025 Q1            FIBEX ARAGUA           43141  2025-11-15
..                ...                     ...             ...         ...
788       ABR 2026 Q1          FIBEX VALENCIA           79681  2026-04-15
789       ABR 2026 Q1             FIBEX YAGUA            1479  2026-04-15
790       ABR 2026 Q1        FIBEX PORTUGUESA            1120  2026-04-15
791       ABR 2026 Q1  FIBEX ARAGUA - MATURIN            1311  2026-04-15
792       ABR 2026 Q1             FIBEX BELEN             408  2026-04-15

[793 rows x 4 columns]