Objetivo: Probar la lógica de limpieza de tiempos negativos y validación de outliers usando .mask() antes de pasarlo al script maestro.
Autor: José Arturo Pérez Falcón
Fecha: Febrero 2026

In [16]:
import pandas as pd

df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Silver_PBI_Final.parquet')
df.info()
print(df.describe())
display(df)

""" # 1. Le decimos a Pandas que repita cada fila el número de veces que diga 'Total_Ordenes'
# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente
df_prueba = df.loc[df.index.repeat(df['Total_Ordenes'])]

# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación
display(df_prueba.groupby('Clasificacion')['SLA Resolucion Min'].median())
display(df) """

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133197 entries, 0 to 133196
Data columns (total 6 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   N° Orden            133197 non-null  object
 1   Quincena Evaluada   133197 non-null  object
 2   Franquicia          133197 non-null  object
 3   Clasificacion       133197 non-null  object
 4   SLA Resolucion Min  133197 non-null  float64
 5   SLA_Bin             133197 non-null  float64
dtypes: float64(2), object(4)
memory usage: 6.1+ MB
       SLA Resolucion Min        SLA_Bin
count       133197.000000  133197.000000
mean          1355.432149    1351.047899
std           3152.603756    3152.534176
min              1.000000       1.000000
25%             83.000000      80.000000
50%            194.000000     190.000000
75%           1526.000000    1520.000000
max          65035.000000   65030.000000

,N° Orden,Quincena Evaluada,Franquicia,Clasificacion,SLA Resolucion Min,SLA_Bin
0,V120861,AGO 2025 Q1,FIBEX VALENCIA,NOC,36.0,30.0
1,VC112838,AGO 2025 Q1,FIBEX VILLA DE CURA,NOC,50.0,50.0
2,GU118214,AGO 2025 Q1,FIBEX GUARICO,NOC,22.0,20.0
3,C114940,AGO 2025 Q1,FIBEX CARACAS,MESA DE CONTROL,1.0,1.0
4,V134699,AGO 2025 Q1,FIBEX VALENCIA,MESA DE CONTROL,5522.0,5520.0
...,...,...,...,...,...,...
133192,MAR168126,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,7570.0,7570.0
133193,MAR171435,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,5052.0,5050.0
133194,MAR168139,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,6788.0,6780.0
133195,LCH339531,FEB 2026 Q1,FIBEX ANZOATEGUI,MESA DE CONTROL,19.0,10.0
133196,MAR173453,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,16.0,10.0

' # 1. Le decimos a Pandas que repita cada fila el número de veces que diga \'Total_Ordenes\'\n# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente\ndf_prueba = df.loc[df.index.repeat(df[\'Total_Ordenes\'])]\n\n# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación\ndisplay(df_prueba.groupby(\'Clasificacion\')[\'SLA Resolucion Min\'].median())\ndisplay(df) '

In [14]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')

display(df)

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden,SLA Detalle Texto
0,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-01,2026-02-01 15:16:00,NaT,2026-02-01,NaT,1,0,...,BJ2890,BJ6465,ACTIVO,FINALIZADA,JOTARAZONA,RYZORRILLA,CARLGONZALEZ,CONFIGURACION DE EQUIPO,CAIDAS SEGUIDAS DE INTERNET,None
1,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-01,2026-02-01 14:58:00,NaT,2026-02-01,NaT,1,0,...,V93453,V175527,ACTIVO,FINALIZADA,CALVAREZ,BLCARRILO,JYAMARTE,REEMPALME DE HILO,SIN INTERNET,None
2,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02,2026-02-02 07:18:00,NaT,2026-02-02,NaT,1,0,...,BJ0790,BJ8653,ACTIVO,FINALIZADA,JOTARAZONA,RYZORRILLA,RYZORRILLA,CONECTOR DAñADO,FALLA LOS,None
3,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02,2026-02-02 07:55:00,NaT,2026-02-02,NaT,1,0,...,MB0280,MB5761,ACTIVO,IMPRESA,None,RYZORRILLA,RYZORRILLA,None,CAIDAS SEGUIDAS DE INTERNET,None
4,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02,2026-02-02 08:27:00,NaT,2026-02-02,NaT,1,0,...,MB1385,MB5762,ACTIVO,IMPRESA,None,RYZORRILLA,RYZORRILLA,None,FALLA LOS,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12378,MAR 2026 Q1,2026-02-01,2026-03-15,2026-03-03,2026-03-03 23:43:00,2026-03-03 23:43:00,2026-03-03,2026-03-03,1,1,...,LCH2359,LCH350823,ACTIVO,FINALIZADA,JBAEZ,APICONEXVE,JBAEZ,REINICIAR EQUIPO,CAIDAS SEGUIDAS DE INTERNET,0 days 23:43:00
12379,MAR 2026 Q1,2026-02-01,2026-03-15,2026-03-03,2026-03-03 23:47:00,2026-03-03 23:47:00,2026-03-03,2026-03-03,1,1,...,C8895,C248777,ACTIVO,FINALIZADA,JBAEZ,APICONEXVE,JBAEZ,REINICIAR EQUIPO,INTERNET LENTO,0 days 23:47:00
12380,MAR 2026 Q1,2026-02-01,2026-03-15,2026-03-03,2026-03-03 23:51:00,2026-03-03 23:51:00,2026-03-03,2026-03-03,1,1,...,V11465,V405134,ACTIVO,FINALIZADA,JBAEZ,APICONEXVE,JBAEZ,REINICIAR EQUIPO,INTERNET LENTO,0 days 23:51:00
12381,MAR 2026 Q1,2026-02-01,2026-03-15,2026-03-03,2026-03-03 23:52:00,2026-03-03 23:52:00,2026-03-03,2026-03-03,1,1,...,V13677,V405135,ACTIVO,FINALIZADA,JBAEZ,APICONEXVE,JBAEZ,REINICIAR EQUIPO,INTERNET LENTO,0 days 23:52:00
12382,MAR 2026 Q1,2026-02-01,2026-03-15,2026-03-03,2026-03-03 23:53:00,2026-03-03 23:54:00,2026-03-03,2026-03-03,1,1,...,C51536,C248779,ACTIVO,FINALIZADA,JBAEZ,APICONEXVE,JBAEZ,REINICIAR EQUIPO,INTERNET LENTO,0 days 23:54:00

In [3]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet')
df.groupby(['Quincena Evaluada','Clasificacion']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()

   Quincena Evaluada    Clasificacion     SLA
0        AGO 2025 Q1  MESA DE CONTROL  1093.5
1        AGO 2025 Q1              NOC    89.0
2        AGO 2025 Q1      OPERACIONES  5732.0
3        AGO 2025 Q2  MESA DE CONTROL  1206.0
4        AGO 2025 Q2              NOC   158.0
5        AGO 2025 Q2      OPERACIONES  5580.5
6        DIC 2025 Q1  MESA DE CONTROL   165.0
7        DIC 2025 Q1              NOC    75.0
8        DIC 2025 Q1      OPERACIONES  1479.5
9        DIC 2025 Q2  MESA DE CONTROL   148.0
10       DIC 2025 Q2              NOC    78.0
11       DIC 2025 Q2      OPERACIONES  1342.0
12       ENE 2026 Q1  MESA DE CONTROL   141.0
13       ENE 2026 Q1              NOC    99.0
14       ENE 2026 Q1      OPERACIONES  1136.5
15       ENE 2026 Q2  MESA DE CONTROL   208.0
16       ENE 2026 Q2              NOC   101.0
17       ENE 2026 Q2      OPERACIONES  1437.5
18       FEB 2026 Q1  MESA DE CONTROL   186.0
19       FEB 2026 Q1              NOC   101.0
20       FEB 2026 Q1      OPERACIONES  1504.0
21       FEB 2026 Q2  MESA DE CONTROL   442.0
22       FEB 2026 Q2              NOC   105.0
23       FEB 2026 Q2      OPERACIONES  1647.0
24       MAR 2026 Q1  MESA DE CONTROL   279.0
25       MAR 2026 Q1              NOC    96.0
26       MAR 2026 Q1      OPERACIONES  1606.5
27       NOV 2025 Q1  MESA DE CONTROL   205.0
28       NOV 2025 Q1              NOC    55.0
29       NOV 2025 Q1      OPERACIONES  2772.0
30       NOV 2025 Q2  MESA DE CONTROL   433.5
31       NOV 2025 Q2              NOC    48.0
32       NOV 2025 Q2      OPERACIONES  1720.0
33       OCT 2025 Q1  MESA DE CONTROL   238.5
34       OCT 2025 Q1              NOC   110.0
35       OCT 2025 Q1      OPERACIONES  2494.0
36       OCT 2025 Q2  MESA DE CONTROL   228.0
37       OCT 2025 Q2              NOC   106.5
38       OCT 2025 Q2      OPERACIONES  2666.5
39       SEP 2025 Q1  MESA DE CONTROL   572.0
40       SEP 2025 Q1              NOC   130.0
41       SEP 2025 Q1      OPERACIONES  2973.0
42       SEP 2025 Q2  MESA DE CONTROL   458.0
43       SEP 2025 Q2              NOC   136.0
44       SEP 2025 Q2      OPERACIONES  1856.0