Objetivo: Probar la lógica de limpieza de tiempos negativos y validación de outliers usando .mask() antes de pasarlo al script maestro.
Autor: José Arturo Pérez Falcón
Fecha: Febrero 2026

In [2]:
import pandas as pd

df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Silver_PBI_Final.parquet')
df.info()
print(df.describe())
display(df)

""" # 1. Le decimos a Pandas que repita cada fila el número de veces que diga 'Total_Ordenes'
# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente
df_prueba = df.loc[df.index.repeat(df['Total_Ordenes'])]

# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación
display(df_prueba.groupby('Clasificacion')['SLA Resolucion Min'].median())
display(df) """

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\josperez\\Documents\\A-DataStack\\01-Proyectos\\01-Data_PipelinesFibex\\02_Data_Lake\\gold_data\\Silver_PBI_Final.parquet'

In [1]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')

display(df)

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,Clasificacion,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden
0,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-10 10:36:00,2026-03-10 11:33:00,NaT,2026-03-10,NaT,1,0,...,MESA DE CONTROL,1142,008612,ACTIVO,IMPRESA,<NA>,JGMEZA,JYAMARTE,<NA>,CAIDAS SEGUIDAS DE INTERNET
1,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-31 13:34:00,2026-03-31 14:08:00,NaT,2026-03-31,NaT,1,0,...,MESA DE CONTROL,1213,010074,ACTIVO,IMPRESA,<NA>,APICONEXVE,DFUENTES,<NA>,SIN INTERNET
2,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 14:12:00,2026-04-01 15:20:00,NaT,2026-04-01,NaT,1,0,...,OPERACIONES,MI1332,MI206221,ACTIVO,IMPRESA,<NA>,YATOVAR,VGAMEZ,<NA>,FALLA LOS
3,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 16:33:00,2026-04-01 16:35:00,NaT,2026-04-01,NaT,1,0,...,MESA DE CONTROL,MI14186,MI206250,ACTIVO,IMPRESA,<NA>,KCHACON,KCHACON,<NA>,SIN INTERNET
4,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-02 10:28:00,2026-04-02 10:29:00,NaT,2026-04-02,NaT,1,0,...,MESA DE CONTROL,MI13664,MI206305,ACTIVO,IMPRESA,<NA>,ADRROJAS,ADRROJAS,<NA>,CAIDAS SEGUIDAS DE INTERNET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195923,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-11 10:25:00,2026-04-12 18:27:00,2026-04-15 23:48:00,2026-04-11,2026-04-15,1,0,...,MESA DE CONTROL,V4004,V584763,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,NSANTANA,REEMPALME DE HILO,SIN INTERNET
195924,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-15 09:24:00,2026-04-15 23:48:00,2026-04-15 23:49:00,2026-04-15,2026-04-15,1,1,...,MESA DE CONTROL,LCH37147,LCH524185,ACTIVO,FINALIZADA,ANTHGONZALEZ,SMARQUEZ,ANTHGONZALEZ,CONFIGURACION DE EQUIPO,SIN INTERNET
195925,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-13 09:04:00,2026-04-13 17:27:00,2026-04-15 23:50:00,2026-04-13,2026-04-15,1,0,...,MESA DE CONTROL,H5391,V609829,ACTIVO,FINALIZADA,ANQUINTERO,MSANTANA,FRPARRA,REEMPALME DE HILO,SIN INTERNET
195926,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-12 16:45:00,2026-04-13 13:49:00,2026-04-15 23:51:00,2026-04-12,2026-04-15,1,0,...,MESA DE CONTROL,V77733,V591199,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,FLEAL,REEMPALME DE HILO,SIN INTERNET
195927,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-15 09:27:00,2026-04-15 23:56:00,2026-04-15 23:58:00,2026-04-15,2026-04-15,1,1,...,MESA DE CONTROL,LCH47358,LCH524208,ACTIVO,FINALIZADA,ANTHGONZALEZ,BLCARRILO,ANTHGONZALEZ,FALLA DE DFS,USUARIO CLAVE ONT

In [5]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet')
df.groupby(['Quincena Evaluada','Clasificacion']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()
df.pivot_table(index='Quincena Evaluada', columns='Clasificacion', values='SLA Resolucion Min', aggfunc='median')

Clasificacion      MESA DE CONTROL    NOC  OPERACIONES
Quincena Evaluada
ABR 2026 Q1                  984.0  244.0       1550.0
AGO 2025 Q1                 1131.0   90.0       5838.0
AGO 2025 Q2                 1249.0  163.0       5391.0
DIC 2025 Q1                  172.0   76.0       1501.0
DIC 2025 Q2                  154.0   82.0       1321.0
ENE 2026 Q1                  145.0  102.0       1145.0
ENE 2026 Q2                  219.0  103.0       1436.0
FEB 2026 Q1                  198.0  102.0       1505.0
FEB 2026 Q2                  456.0  109.0       1647.0
MAR 2026 Q1                  294.0  100.0       1609.0
MAR 2026 Q2                  273.0   85.0       1546.0
NOV 2025 Q1                  210.0   55.0       2771.0
NOV 2025 Q2                  454.0   49.0       1720.0
OCT 2025 Q1                  259.0  113.0       2593.0
OCT 2025 Q2                  237.0  112.0       2584.0
SEP 2025 Q1                  938.0  133.0       2973.0
SEP 2025 Q2                  545.5  137.0       1863.0

In [ ]:
import pandas as pd
df = pd.read_excel(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet',engine = 'calamine')

In [34]:
import pandas as pd
idf_detalle = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\IDF_Gold_Detalle_Solucion.parquet')
idf = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\IDF_Gold.parquet')
franq = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Stock_Abonados_Gold_Resumen.parquet')
#idf1 = idf.groupby('Quincena Evaluada').agg( IDF = ('Total_Fallas', 'sum') ).reset_index()
display(idf.groupby('Quincena Evaluada').agg( IDF = ('Total_Fallas', 'sum') ).reset_index())
display(idf_detalle.groupby('Quincena Evaluada').agg( IDF =('Total_Ordenes','sum')))
display(franq)

   Quincena Evaluada    IDF
0        ABR 2026 Q1  12781
1        AGO 2025 Q1   9757
2        AGO 2025 Q2  10850
3        DIC 2025 Q1   9641
4        DIC 2025 Q2  10075
5        ENE 2026 Q1  16252
6        ENE 2026 Q2  13675
7        FEB 2026 Q1  10991
8        FEB 2026 Q2  10751
9        MAR 2026 Q1  11007
10       MAR 2026 Q2  13196
11       NOV 2025 Q1   9278
12       NOV 2025 Q2   9469
13       OCT 2025 Q1   9747
14       OCT 2025 Q2  11707
15       SEP 2025 Q1  10211
16       SEP 2025 Q2  10502

                     IDF
Quincena Evaluada
ABR 2026 Q1        14287
AGO 2025 Q1         9758
AGO 2025 Q2        10850
DIC 2025 Q1         9644
DIC 2025 Q2        10501
ENE 2026 Q1        10006
ENE 2026 Q2        13983
FEB 2026 Q1        10991
FEB 2026 Q2        10761
MAR 2026 Q1        11006
MAR 2026 Q2        13297
NOV 2025 Q1         9795
NOV 2025 Q2         9591
OCT 2025 Q1         9745
OCT 2025 Q2        11699
SEP 2025 Q1        10211
SEP 2025 Q2        10495

    Quincena Evaluada          Franquicia  Total_Abonados Fecha_Corte
0         AGO 2025 Q1  FIBEX LAS ADJUNTAS            6115  2025-08-15
1         AGO 2025 Q1       FIBEX MARIARA            4567  2025-08-15
2         AGO 2025 Q1   FIBEX PTO CABELLO            7602  2025-08-15
3         AGO 2025 Q1        FIBEX SARARE            1532  2025-08-15
4         OCT 2025 Q1       FIBEX CARACAS           26894  2025-10-15
..                ...                 ...             ...         ...
788       SEP 2025 Q1     FIBEX LAGUNITAS            1080  2025-09-15
789       FEB 2026 Q2     FIBEX YARITAGUA            3393  2026-02-28
790       FEB 2026 Q2    FIBEX SAN CARLOS           14374  2026-02-28
791       ABR 2026 Q1       FIBEX MIRANDA           10893  2026-04-15
792       ABR 2026 Q1     FIBEX LAGUNITAS             982  2026-04-15

[793 rows x 4 columns]

In [32]:
import pandas as pd

# 1. Carga de datos
df_ONT = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\ONT_OFF_Gold.parquet')
df_total = pd.read_excel(r'C:\Users\josperez\Downloads\ACTIVOS POWER FAIL.xlsx', sheet_name='SMART POWER FAIL')

# --- SOLUCIÓN AL ERROR DE TIPO ---
# Convertimos ambas columnas de unión a String y quitamos espacios en blanco
df_ONT['N° Abonado'] = df_ONT['N° Abonado'].astype(str).str.strip()
df_total['Name'] = df_total['Name'].astype(str).str.strip()
display(df_total)
display(df_total.columns)
df_total = df_total[df_total['Estatus'] == 'ACTIVO'] # Filtramos solo los activos
# 2. Merge tipo 'outer' con indicador
df_merge = pd.merge(
    df_ONT, 
    df_total, 
    how='outer', 
    left_on='N° Abonado', 
    right_on='Name', 
    indicator=True
)

# 3. Filtrar para mantener solo lo que está en la derecha (los que no están en el Gold)
df_solo_derecha = df_merge[df_merge['_merge'] == 'right_only'].copy()

# 4. Limpieza
df_solo_derecha = df_solo_derecha.drop(columns=['_merge'])

display(df_solo_derecha)

,ONU external ID,PON Type,SN,Onu Type,Name,OLT,Board,Port,Estado,Estatus,...,Service port VLAN,Service port CVLAN,Service port SVLAN,Service port tag transform mode,Service port upload speed,Service port download speed,Contact,TR069 Profile,TR069 Device ID,Last status change
0,HWTC110E27A1,gpon,HWTC110E27A1,HG8126,A49029,OLT-HUAWEI-EUROBUILDING,17,12,ARAGUA,ACTIVO,...,100,NaN,5.0,translate,-traffic-table_310,-traffic-table_310,NaN,NaN,NaN,2026-03-23 06:51:07
1,FBEXFE1E022A,gpon,FBEXFE1E022A,IGD,V80762,OLT-HUAWEI-PARRAL,3,9,NaN,NaN,...,100,NaN,15.0,translate,FTTH_600,FTTH_600,NaN,NaN,NaN,2026-03-23 06:54:59
2,TPLG1502BF10,gpon,TPLG1502BF10,XC220-G3v,A70950,OLT-HUAWEI-CAGUA,4,14,NaN,NaN,...,100,NaN,18.0,translate,FTTH_300,FTTH_300,NaN,NaN,NaN,2026-03-23 06:59:33
3,FBEXFE1BF23E,gpon,FBEXFE1BF23E,IGD,V29952,OLT-HUAWEI-TOCUYITO,14,15,CARABOBO,ACTIVO,...,100,NaN,3.0,translate,-traffic-table_304,-traffic-table_304,NaN,NaN,NaN,2026-03-23 07:18:27
4,HWTCA9C849A5,gpon,HWTCA9C849A5,HG8010Hv6,LCH15538,OLT-HUAWEI-GUANTA,15,1,NaN,NaN,...,100,NaN,17.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-03-23 07:42:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824,SKYWB80F5C87,gpon,SKYWB80F5C87,GN630V,AP2124,OLT-HUAWEI-SAN-FERNANDO-DE-APURE,5,12,NaN,NaN,...,100,NaN,2527.0,translate,PYME_35,PYME_35,NaN,NaN,NaN,2026-04-23 14:43:38
5825,SKYWB81F26A9,gpon,SKYWB81F26A9,GN630V,AP5093,OLT-HUAWEI-SAN-FERNANDO-DE-APURE,9,0,NaN,NaN,...,100,NaN,2527.0,translate,FTTH_35,FTTH_35,NaN,NaN,NaN,2026-04-23 14:43:38
5826,SKYWB81F5557,gpon,SKYWB81F5557,GN630V,GU51558,OLT-HUAWEI-CALABOZO-II,10,13,NaN,NaN,...,100,NaN,2552.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-23 14:43:51
5827,SKYWB80F475E,gpon,SKYWB80F475E,GN630V,GU39135,OLT-HUAWEI-CALABOZO-II,12,6,NaN,NaN,...,100,NaN,2554.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-23 14:43:51
5828,SKYWB80729FF,gpon,SKYWB80729FF,GN630V,GU39002,OLT-HUAWEI-CALABOZO-II,15,5,NaN,NaN,...,100,NaN,2554.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-23 14:43:51

Index(['ONU external ID', 'PON Type', 'SN', 'Onu Type', 'Name', 'OLT', 'Board',
       'Port', 'Estado', 'Estatus', 'Allocated ONU', 'Zone', 'Address',
       'Latitude', 'Longitude', 'ODB (Splitter)', 'ODB Port', 'Mode',
       'WAN mode', 'IP address', 'Subnet mask', 'Default gateway', 'DNS1',
       'DNS2', 'Username', 'Password', 'CATV', 'Administrative status',
       'Auth date', 'Status', 'Signal', 'Signal 1310', 'Signal 1490',
       'Distance(m)', 'Service port', 'Service port VLAN',
       'Service port CVLAN', 'Service port SVLAN',
       'Service port tag transform mode', 'Service port upload speed',
       'Service port download speed', 'Contact', 'TR069 Profile',
       'TR069 Device ID', 'Last status change'],
      dtype='object')

,N° Abonado,Documento,Cliente,Estatus_x,Fecha,Hora,Tipo Llamada,Tipo Respuesta,Detalle Respuesta,Vendedor,...,Service port VLAN,Service port CVLAN,Service port SVLAN,Service port tag transform mode,Service port upload speed,Service port download speed,Contact,TR069 Profile,TR069 Device ID,Last status change
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2404.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-07 11:55:30
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-16 13:11:38
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-15 12:12:39
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-21 09:40:38
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2404.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-02 10:24:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,11.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-15 09:37:57
1683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,6.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-16 10:34:16
1719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2239.0,translate,FTTH_600,FTTH_600,NaN,NaN,NaN,2026-04-20 10:30:22
1743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,59.0,translate,PYME_60,PYME_60,NaN,NaN,NaN,2026-04-19 20:03:16
1747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,3.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-20 12:54:43

In [36]:
import pandas as pd

# 1. Carga de datos
df_ONT = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\ONT_OFF_Gold.parquet')
df_ONT.to_excel(r'C:\Users\josperez\Downloads\ONT_OFF_Gold.xlsx', index=False)