Objetivo: Probar la lógica de limpieza de tiempos negativos y validación de outliers usando .mask() antes de pasarlo al script maestro.
Autor: José Arturo Pérez Falcón
Fecha: Febrero 2026

In [38]:
import pandas as pd

df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')
df.info()
print(df.describe())
display(df)

# 1. Le decimos a Pandas que repita cada fila el número de veces que diga 'Total_Ordenes'
# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente
df_prueba = df
# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación
display(df_prueba.groupby(['Quincena Evaluada','Clasificacion'],as_index=False).agg(Mediana = ('SLA Resolucion Min', 'median'), 
                                                                                    Promedio = ('SLA Resolucion Min', 'mean')))
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199143 entries, 0 to 199142
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Quincena Evaluada    199143 non-null  object
 1   FechaInicio          199143 non-null  datetime64[us]
 2   FechaFin             199143 non-null  datetime64[us]
 3   Fecha Apertura       199143 non-null  datetime64[ns]
 4   Fecha Impresion      198623 non-null  datetime64[ns]
 5   Fecha Cierre         196836 non-null  datetime64[ns]
 6   Fecha Apertura Date  199143 non-null  datetime64[ns]
 7   Fecha Cierre Date    196836 non-null  datetime64[ns]
 8   Es_Falla             199143 non-null  int64
 9   Cumplio_SLA          199143 non-null  int64
 10  Duracion_Horas       196836 non-null  float64
 11  SLA Resolucion Min   196836 non-null  float64
 12  SLA Despacho Min     196819 non-null  float64
 13  SLA Impresion Min    198623 non-null  float64
 14  Franquicia           199143 non-null  large_string[pyarrow]
 15  Grupo Trabajo        198584 non-null  large_string[pyarrow]
 16  Grupo Afinidad       199143 non-null  large_string[pyarrow]
 17  Clasificacion        199143 non-null  object
 18  N° Contrato          199143 non-null  large_string[pyarrow]
 19  N° Orden             199143 non-null  large_string[pyarrow]
 20  Estatus contrato     199143 non-null  large_string[pyarrow]
 21  Estatus_orden        199143 non-null  large_string[pyarrow]
 22  Usuario Final        196832 non-null  large_string[pyarrow]
 23  Usuario Emisión      199143 non-null  large_string[pyarrow]
 24  Usuario Impresión    198623 non-null  large_string[pyarrow]
 25  Solucion Aplicada    195893 non-null  large_string[pyarrow]
 26  Detalle Orden        199143 non-null  large_string[pyarrow]
dtypes: datetime64[ns](5), datetime64[us](2), float64(4), int64(2), large_string[pyarrow](12), object(2)
memory usage: 65.1+ MB
                      FechaInicio                    FechaFin  \
count                      199143                      199143
mean   2025-11-14 11:24:53.397207  2025-12-29 15:04:51.824467
min           2025-07-01 00:00:00         2025-08-15 00:00:00
25%           2025-09-01 00:00:00         2025-10-15 00:00:00
50%           2025-11-15 00:00:00         2025-12-31 00:00:00
75%           2026-02-01 00:00:00         2026-03-15 00:00:00
max           2026-03-15 00:00:00         2026-04-30 00:00:00
std                           NaN                         NaN

                      Fecha Apertura                Fecha Impresion  \
count                         199143                         198623
mean   2025-12-21 23:34:31.704252672  2025-12-21 20:19:17.922697984
min              2025-07-03 12:54:00            2025-07-03 14:21:00
25%              2025-10-13 10:23:00            2025-10-13 10:07:30
50%              2025-12-24 14:33:00            2025-12-23 21:06:00
75%              2026-03-03 07:53:30            2026-03-02 15:26:00
max              2026-04-30 23:53:00            2026-05-05 09:51:00
std                              NaN                            NaN

                        Fecha Cierre            Fecha Apertura Date  \
count                         196836                         199143
mean   2025-12-22 11:28:30.572456192  2025-12-21 10:20:57.649026304
min              2025-08-01 05:36:00            2025-07-03 00:00:00
25%              2025-10-13 12:51:00            2025-10-13 00:00:00
50%              2025-12-26 10:51:00            2025-12-24 00:00:00
75%              2026-03-03 12:59:00            2026-03-03 00:00:00
max              2026-04-30 23:53:00            2026-04-30 00:00:00
std                              NaN                            NaN

                   Fecha Cierre Date  Es_Falla    Cumplio_SLA  Duracion_Horas  \
count                         196836  199143.0  199143.000000   196836.000000
mean   2025-12-21 21:29:26.091568640       1.0       0.686150       22.234719
min              2025-08-01 00:00:00       1.0       0.000000     -165.816667
25%              2025-10-13 00:00:00       1.0       0.000000        1.450000
50%              2025-12-26 00:00:00       1.0       1.000000        3.833333
75%              2026-03-03 00:00:00       1.0       1.000000       26.166667
max              2026-04-30 00:00:00       1.0       1.000000     1083.916667
std                              NaN       0.0       0.464057       49.667554

       SLA Resolucion Min  SLA Despacho Min  SLA Impresion Min
count       196836.000000     196819.000000      198623.000000
mean          1334.083115       1084.240932         250.414922
min          -9949.000000     -23039.000000           0.000000
25%             87.000000          1.000000          17.000000
50%            230.000000          8.000000          76.000000
75%           1570.000000       1355.000000         143.000000
max          65035.000000      65017.000000       62066.000000
std           2980.053254       2892.781426         883.615478

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,Clasificacion,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden
0,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-10 10:36:00,2026-03-10 11:33:00,NaT,2026-03-10,NaT,1,0,...,MESA DE CONTROL,1142,008612,ACTIVO,IMPRESA,<NA>,JGMEZA,JYAMARTE,<NA>,CAIDAS SEGUIDAS DE INTERNET
1,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 20:18:00,2026-04-01 20:19:00,NaT,2026-04-01,NaT,1,0,...,OPERACIONES,V36053,V519443,ACTIVO,IMPRESA,<NA>,ANTHGONZALEZ,ANTHGONZALEZ,<NA>,FALLA LOS
2,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-03 19:01:00,2026-04-03 20:54:00,NaT,2026-04-03,NaT,1,0,...,OPERACIONES,MI11720,MI206412,ACTIVO,IMPRESA,<NA>,WILESCOBAR,FRPARRA,<NA>,FALLA LOS
3,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-03 19:02:00,2026-04-03 20:55:00,NaT,2026-04-03,NaT,1,0,...,OPERACIONES,MI9757,MI206413,ACTIVO,IMPRESA,<NA>,WILESCOBAR,FRPARRA,<NA>,FALLA LOS
4,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-02 22:15:00,2026-04-03 00:10:00,NaT,2026-04-02,NaT,1,0,...,OPERACIONES,V131331,V519887,ACTIVO,IMPRESA,<NA>,APICONEXVE,ANTHGONZALEZ,<NA>,SIN INTERNET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199138,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 09:36:00,2026-04-30 10:35:00,2026-04-30 23:42:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,V135518,V654689,ACTIVO,FINALIZADA,ANQUINTERO,MAAVILA,LLZERPA,FALLA GENERAL,SIN INTERNET
199139,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 17:26:00,2026-04-30 11:16:00,2026-04-30 23:43:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,LS0124,LS158307,ACTIVO,FINALIZADA,CLTORRES,AIHPV,LJVILLEGAS,FALLA GENERAL,INTERNET LENTO
199140,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 08:57:00,2026-04-30 09:35:00,2026-04-30 23:43:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,V52781,V654630,ACTIVO,FINALIZADA,ANQUINTERO,JAPONTE,LLZERPA,FALLA GENERAL,SIN INTERNET
199141,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-30 11:46:00,2026-04-30 17:37:00,2026-04-30 23:44:00,2026-04-30,2026-04-30,1,1,...,MESA DE CONTROL,C10082,C334615,ACTIVO,FINALIZADA,CLTORRES,APICONEXVE,DIREYES,FALLA LOS,SIN INTERNET
199142,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 10:55:00,2026-04-30 11:35:00,2026-04-30 23:53:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,MAR5828,MAR189134,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,LLZERPA,FALLA GENERAL,SIN INTERNET

   Quincena Evaluada    Clasificacion  Mediana      Promedio
0        ABR 2026 Q1  MESA DE CONTROL    861.0   1278.024198
1        ABR 2026 Q1              NOC    194.5    622.640034
2        ABR 2026 Q1      OPERACIONES   1550.0   2270.400000
3        ABR 2026 Q2  MESA DE CONTROL   1648.0   2118.508740
4        ABR 2026 Q2              NOC   1590.5   1706.342322
5        ABR 2026 Q2      OPERACIONES   1419.5   2145.542071
6        AGO 2025 Q1  MESA DE CONTROL   1098.0   1949.666051
7        AGO 2025 Q1              NOC     88.0     65.145315
8        AGO 2025 Q1      OPERACIONES   5838.0  11211.738462
9        AGO 2025 Q2  MESA DE CONTROL   1207.0   2173.783439
10       AGO 2025 Q2              NOC    159.0    150.667487
11       AGO 2025 Q2      OPERACIONES   5391.0  14562.541667
12       DIC 2025 Q1  MESA DE CONTROL    163.5   1080.287234
13       DIC 2025 Q1              NOC     75.0     56.017356
14       DIC 2025 Q1      OPERACIONES   1496.0   2294.320611
15       DIC 2025 Q2  MESA DE CONTROL    149.0   1201.035969
16       DIC 2025 Q2              NOC     78.0     61.898281
17       DIC 2025 Q2      OPERACIONES   1328.0   2163.851852
18       ENE 2026 Q1  MESA DE CONTROL    142.0   1591.895450
19       ENE 2026 Q1              NOC     99.0    136.801009
20       ENE 2026 Q1      OPERACIONES   1135.0   1775.834568
21       ENE 2026 Q2  MESA DE CONTROL    206.0   1153.703990
22       ENE 2026 Q2              NOC    101.0    122.787425
23       ENE 2026 Q2      OPERACIONES   1436.0   2119.425837
24       FEB 2026 Q1  MESA DE CONTROL    188.0    970.589572
25       FEB 2026 Q1              NOC    101.0     71.900124
26       FEB 2026 Q1      OPERACIONES   1505.0   2625.251938
27       FEB 2026 Q2  MESA DE CONTROL    441.0   1578.490693
28       FEB 2026 Q2              NOC    105.0     93.471465
29       FEB 2026 Q2      OPERACIONES   1647.0   2510.024590
30       MAR 2026 Q1  MESA DE CONTROL    279.0   1246.031823
31       MAR 2026 Q1              NOC     98.0     74.495350
32       MAR 2026 Q1      OPERACIONES   1606.5   2197.695219
33       MAR 2026 Q2  MESA DE CONTROL    249.0   1179.126707
34       MAR 2026 Q2              NOC     84.0     68.289202
35       MAR 2026 Q2      OPERACIONES   1549.0   2086.548944
36       NOV 2025 Q1  MESA DE CONTROL    205.0   1249.986905
37       NOV 2025 Q1              NOC     55.0     63.210029
38       NOV 2025 Q1      OPERACIONES   2771.0   3507.345882
39       NOV 2025 Q2  MESA DE CONTROL    437.5   1942.695190
40       NOV 2025 Q2              NOC     48.0    560.523485
41       NOV 2025 Q2      OPERACIONES   1717.0   2785.698052
42       OCT 2025 Q1  MESA DE CONTROL    238.0   1422.587883
43       OCT 2025 Q1              NOC    111.0     55.165670
44       OCT 2025 Q1      OPERACIONES   2498.0   4430.320665
45       OCT 2025 Q2  MESA DE CONTROL    229.0   1141.675182
46       OCT 2025 Q2              NOC    106.0     90.357829
47       OCT 2025 Q2      OPERACIONES   2646.0   4265.867036
48       SEP 2025 Q1  MESA DE CONTROL    593.0   1878.413618
49       SEP 2025 Q1              NOC    130.0     94.019341
50       SEP 2025 Q1      OPERACIONES   2957.0   6275.973684
51       SEP 2025 Q2  MESA DE CONTROL    453.0   1793.849906
52       SEP 2025 Q2              NOC    135.0    110.796562
53       SEP 2025 Q2      OPERACIONES   1863.0   3929.414966

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,Clasificacion,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden
0,ABR 2026 Q1,2026-03-01,2026-04-15,2026-03-10 10:36:00,2026-03-10 11:33:00,NaT,2026-03-10,NaT,1,0,...,MESA DE CONTROL,1142,008612,ACTIVO,IMPRESA,<NA>,JGMEZA,JYAMARTE,<NA>,CAIDAS SEGUIDAS DE INTERNET
1,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-01 20:18:00,2026-04-01 20:19:00,NaT,2026-04-01,NaT,1,0,...,OPERACIONES,V36053,V519443,ACTIVO,IMPRESA,<NA>,ANTHGONZALEZ,ANTHGONZALEZ,<NA>,FALLA LOS
2,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-03 19:01:00,2026-04-03 20:54:00,NaT,2026-04-03,NaT,1,0,...,OPERACIONES,MI11720,MI206412,ACTIVO,IMPRESA,<NA>,WILESCOBAR,FRPARRA,<NA>,FALLA LOS
3,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-03 19:02:00,2026-04-03 20:55:00,NaT,2026-04-03,NaT,1,0,...,OPERACIONES,MI9757,MI206413,ACTIVO,IMPRESA,<NA>,WILESCOBAR,FRPARRA,<NA>,FALLA LOS
4,ABR 2026 Q1,2026-03-01,2026-04-15,2026-04-02 22:15:00,2026-04-03 00:10:00,NaT,2026-04-02,NaT,1,0,...,OPERACIONES,V131331,V519887,ACTIVO,IMPRESA,<NA>,APICONEXVE,ANTHGONZALEZ,<NA>,SIN INTERNET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199138,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 09:36:00,2026-04-30 10:35:00,2026-04-30 23:42:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,V135518,V654689,ACTIVO,FINALIZADA,ANQUINTERO,MAAVILA,LLZERPA,FALLA GENERAL,SIN INTERNET
199139,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 17:26:00,2026-04-30 11:16:00,2026-04-30 23:43:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,LS0124,LS158307,ACTIVO,FINALIZADA,CLTORRES,AIHPV,LJVILLEGAS,FALLA GENERAL,INTERNET LENTO
199140,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 08:57:00,2026-04-30 09:35:00,2026-04-30 23:43:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,V52781,V654630,ACTIVO,FINALIZADA,ANQUINTERO,JAPONTE,LLZERPA,FALLA GENERAL,SIN INTERNET
199141,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-30 11:46:00,2026-04-30 17:37:00,2026-04-30 23:44:00,2026-04-30,2026-04-30,1,1,...,MESA DE CONTROL,C10082,C334615,ACTIVO,FINALIZADA,CLTORRES,APICONEXVE,DIREYES,FALLA LOS,SIN INTERNET
199142,ABR 2026 Q2,2026-03-15,2026-04-30,2026-04-29 10:55:00,2026-04-30 11:35:00,2026-04-30 23:53:00,2026-04-29,2026-04-30,1,0,...,MESA DE CONTROL,MAR5828,MAR189134,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,LLZERPA,FALLA GENERAL,SIN INTERNET

In [33]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')
df = df.groupby(['Solucion Aplicada']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()
df = df.sort_values(by='SLA', ascending=False)
display(df)

                                  Solucion Aplicada      SLA
44                                     PAGO CRUZADO  11266.0
46                                   PAGO RECHAZADO  10177.0
40                        NO SABER DESCARGAR LA APP   5105.0
0                              ACTIVACIóN POR SMART   3621.0
6                                    CAJA EXPANDIDA   3282.0
..                                              ...      ...
34  FIBEXPLAY: AJUSTE POR COMPATIBILIDAD DE VERSION     79.0
58                            SERVICIO FILTRADO MAC     78.0
13     CANALES, SIN VIDEO CON AUDIO (NUEVA VERSION)     63.0
45                                   PAGO DUPLICADO     56.0
50       PROBLEMAS PARA ACCEDER A LA APP FIBEX PLAY      1.0

[62 rows x 2 columns]

In [8]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet')
df.groupby(['Quincena Evaluada','Clasificacion']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()
display(df.pivot_table(index='Quincena Evaluada', columns='Clasificacion', values='SLA Resolucion Min', aggfunc='median'))
display(df.pivot_table(index='Quincena Evaluada', columns='Clasificacion', values='SLA Resolucion Min', aggfunc='mean'))

Clasificacion      ADMINISTRATIVO     N/S     NOC  OPERACIONES
Quincena Evaluada
ABR 2026 Q1                 639.0   114.0   465.0       1435.0
ABR 2026 Q2                1589.0  1667.0  1530.0       1714.0
AGO 2025 Q1                2561.0   161.5    97.0       1858.0
AGO 2025 Q2                1729.0   294.0   173.0       1814.0
DIC 2025 Q1                  76.0  1230.0    80.0       1391.0
DIC 2025 Q2                  87.0   173.5    80.0       1355.0
ENE 2026 Q1                 104.5   107.5   101.0       1346.0
ENE 2026 Q2                 113.0   130.0   114.0       1442.0
FEB 2026 Q1                 110.0   148.0   108.0       1347.0
FEB 2026 Q2                 114.0  1092.0   117.0       1408.0
MAR 2026 Q1                 113.5   337.0   118.0       1398.0
MAR 2026 Q2                  93.0   124.0    94.0       1356.5
NOV 2025 Q1                 117.0    95.0    56.0       1399.0
NOV 2025 Q2                 142.0  1292.0    57.0       1389.0
OCT 2025 Q1                1041.0   172.0   123.0       1489.0
OCT 2025 Q2                1276.0   172.5   127.0       1394.0
SEP 2025 Q1                1466.0   219.0   152.0       1873.0
SEP 2025 Q2                1368.0   216.0   145.0       1620.0

Clasificacion      ADMINISTRATIVO          N/S          NOC  OPERACIONES
Quincena Evaluada
ABR 2026 Q1            828.618579   828.884774   846.890829  1986.624504
ABR 2026 Q2           1738.191450  2219.465736  1677.292776  2463.726355
AGO 2025 Q1           3776.600000  1610.361042   372.545204  3068.244392
AGO 2025 Q2           2403.444444  1502.908608   558.179179  3289.961654
DIC 2025 Q1            290.683491  1681.211302   277.515721  1872.614532
DIC 2025 Q2            380.289140  1740.296813   274.391440  2024.552695
ENE 2026 Q1            274.043103  1290.815364   485.775159  2996.152782
ENE 2026 Q2            325.851687  1108.585097   369.184295  2132.166570
FEB 2026 Q1            224.682451  1176.412587   267.050474  1816.815444
FEB 2026 Q2            537.094655  1416.746564   627.930383  2235.866458
MAR 2026 Q1            397.387652   926.635706   521.180589  2039.456297
MAR 2026 Q2            245.244115   940.413223   361.210655  1964.642312
NOV 2025 Q1            411.833333  1158.526882   259.828604  2164.272660
NOV 2025 Q2           5056.579130  2597.631679  1030.379639  1975.049429
OCT 2025 Q1           3099.769231  1459.042772   277.986530  2370.295506
OCT 2025 Q2           1495.500000  1167.550164   279.874468  2084.102974
SEP 2025 Q1           1659.538462  1816.056566   417.209294  3045.418420
SEP 2025 Q2           1445.419355  1539.325390   384.880799  2904.357001

In [36]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\SLA_GOLD_STATS.parquet')
df = df.groupby(['Quincena Evaluada']).agg( SLA = ('SLA Resolucion Min', 'median') ).reset_index()
df = df.sort_values(by='SLA', ascending=False)
display(df)

   Quincena Evaluada     SLA
1        ABR 2026 Q2  1615.0
0        ABR 2026 Q1   846.5
9        FEB 2026 Q2   309.0
13       NOV 2025 Q2   285.0
3        AGO 2025 Q2   279.0
17       SEP 2025 Q2   233.0
16       SEP 2025 Q1   217.0
15       OCT 2025 Q2   211.0
14       OCT 2025 Q1   198.0
10       MAR 2026 Q1   198.0
2        AGO 2025 Q1   197.0
11       MAR 2026 Q2   170.0
7        ENE 2026 Q2   162.0
8        FEB 2026 Q1   142.0
5        DIC 2025 Q2   138.0
6        ENE 2026 Q1   135.0
4        DIC 2025 Q1   130.0
12       NOV 2025 Q1   126.0

In [1]:
import pandas as pd
idf_detalle = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\IDF_Gold_Detalle_Solucion.parquet')
idf = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\IDF_Gold.parquet')
franq = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Stock_Abonados_Gold_Resumen.parquet')
#idf1 = idf.groupby('Quincena Evaluada').agg( IDF = ('Total_Fallas', 'sum') ).reset_index()
display(idf.groupby('Quincena Evaluada').agg( IDF = ('Total_Fallas', 'sum') ).reset_index())
display(idf_detalle.groupby('Quincena Evaluada').agg( IDF =('Total_Ordenes','sum')))
display(franq)

   Quincena Evaluada    IDF
0        ABR 2026 Q1  12114
1        ABR 2026 Q2  14442
2        AGO 2025 Q1   9741
3        AGO 2025 Q2  10866
4        DIC 2025 Q1   9635
5        DIC 2025 Q2  10081
6        ENE 2026 Q1   9395
7        ENE 2026 Q2  13691
8        FEB 2026 Q1  10984
9        FEB 2026 Q2  10758
10       MAR 2026 Q1  11008
11       MAR 2026 Q2  13195
12       NOV 2025 Q1   9285
13       NOV 2025 Q2   9462
14       OCT 2025 Q1   9768
15       OCT 2025 Q2  11686
16       SEP 2025 Q1  10223
17       SEP 2025 Q2  10490

                     IDF
Quincena Evaluada
ABR 2026 Q1        13453
ABR 2026 Q2        13922
AGO 2025 Q1        10118
AGO 2025 Q2        11164
DIC 2025 Q1         9239
DIC 2025 Q2        10703
ENE 2026 Q1         9171
ENE 2026 Q2        13674
FEB 2026 Q1        10057
FEB 2026 Q2        10005
MAR 2026 Q1        10182
MAR 2026 Q2        12329
NOV 2025 Q1        10949
NOV 2025 Q2         9472
OCT 2025 Q1        10256
OCT 2025 Q2        11936
SEP 2025 Q1        10582
SEP 2025 Q2        10714

    Quincena Evaluada          Franquicia  Total_Abonados Fecha_Corte
0         FEB 2026 Q2         FIBEX MORON            3273  2026-02-28
1         FEB 2026 Q2   FIBEX SAN JOAQUIN            2797  2026-02-28
2         FEB 2026 Q2     FIBEX MARGARITA           10273  2026-02-28
3         OCT 2025 Q1       FIBEX GUARICO           37764  2025-10-15
4         OCT 2025 Q1  FIBEX BARQUISIMETO           18811  2025-10-15
..                ...                 ...             ...         ...
835       OCT 2025 Q2        FIBEX BEJUMA            2026  2025-10-31
836       OCT 2025 Q2    FIBEX SAN RAFAEL            2953  2025-10-31
837       OCT 2025 Q2     FIBEX URACHICHE             438  2025-10-31
838       ABR 2026 Q1       FIBEX CHIRGUA             167  2026-04-15
839       ABR 2026 Q2     FIBEX MAGDALENO             269  2026-04-30

[840 rows x 4 columns]

In [32]:
import pandas as pd

# 1. Carga de datos
df_ONT = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\ONT_OFF_Gold.parquet')
df_total = pd.read_excel(r'C:\Users\josperez\Downloads\ACTIVOS POWER FAIL.xlsx', sheet_name='SMART POWER FAIL')

# --- SOLUCIÓN AL ERROR DE TIPO ---
# Convertimos ambas columnas de unión a String y quitamos espacios en blanco
df_ONT['N° Abonado'] = df_ONT['N° Abonado'].astype(str).str.strip()
df_total['Name'] = df_total['Name'].astype(str).str.strip()
display(df_total)
display(df_total.columns)
df_total = df_total[df_total['Estatus'] == 'ACTIVO'] # Filtramos solo los activos
# 2. Merge tipo 'outer' con indicador
df_merge = pd.merge(
    df_ONT, 
    df_total, 
    how='outer', 
    left_on='N° Abonado', 
    right_on='Name', 
    indicator=True
)

# 3. Filtrar para mantener solo lo que está en la derecha (los que no están en el Gold)
df_solo_derecha = df_merge[df_merge['_merge'] == 'right_only'].copy()

# 4. Limpieza
df_solo_derecha = df_solo_derecha.drop(columns=['_merge'])

display(df_solo_derecha)

,ONU external ID,PON Type,SN,Onu Type,Name,OLT,Board,Port,Estado,Estatus,...,Service port VLAN,Service port CVLAN,Service port SVLAN,Service port tag transform mode,Service port upload speed,Service port download speed,Contact,TR069 Profile,TR069 Device ID,Last status change
0,HWTC110E27A1,gpon,HWTC110E27A1,HG8126,A49029,OLT-HUAWEI-EUROBUILDING,17,12,ARAGUA,ACTIVO,...,100,NaN,5.0,translate,-traffic-table_310,-traffic-table_310,NaN,NaN,NaN,2026-03-23 06:51:07
1,FBEXFE1E022A,gpon,FBEXFE1E022A,IGD,V80762,OLT-HUAWEI-PARRAL,3,9,NaN,NaN,...,100,NaN,15.0,translate,FTTH_600,FTTH_600,NaN,NaN,NaN,2026-03-23 06:54:59
2,TPLG1502BF10,gpon,TPLG1502BF10,XC220-G3v,A70950,OLT-HUAWEI-CAGUA,4,14,NaN,NaN,...,100,NaN,18.0,translate,FTTH_300,FTTH_300,NaN,NaN,NaN,2026-03-23 06:59:33
3,FBEXFE1BF23E,gpon,FBEXFE1BF23E,IGD,V29952,OLT-HUAWEI-TOCUYITO,14,15,CARABOBO,ACTIVO,...,100,NaN,3.0,translate,-traffic-table_304,-traffic-table_304,NaN,NaN,NaN,2026-03-23 07:18:27
4,HWTCA9C849A5,gpon,HWTCA9C849A5,HG8010Hv6,LCH15538,OLT-HUAWEI-GUANTA,15,1,NaN,NaN,...,100,NaN,17.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-03-23 07:42:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824,SKYWB80F5C87,gpon,SKYWB80F5C87,GN630V,AP2124,OLT-HUAWEI-SAN-FERNANDO-DE-APURE,5,12,NaN,NaN,...,100,NaN,2527.0,translate,PYME_35,PYME_35,NaN,NaN,NaN,2026-04-23 14:43:38
5825,SKYWB81F26A9,gpon,SKYWB81F26A9,GN630V,AP5093,OLT-HUAWEI-SAN-FERNANDO-DE-APURE,9,0,NaN,NaN,...,100,NaN,2527.0,translate,FTTH_35,FTTH_35,NaN,NaN,NaN,2026-04-23 14:43:38
5826,SKYWB81F5557,gpon,SKYWB81F5557,GN630V,GU51558,OLT-HUAWEI-CALABOZO-II,10,13,NaN,NaN,...,100,NaN,2552.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-23 14:43:51
5827,SKYWB80F475E,gpon,SKYWB80F475E,GN630V,GU39135,OLT-HUAWEI-CALABOZO-II,12,6,NaN,NaN,...,100,NaN,2554.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-23 14:43:51
5828,SKYWB80729FF,gpon,SKYWB80729FF,GN630V,GU39002,OLT-HUAWEI-CALABOZO-II,15,5,NaN,NaN,...,100,NaN,2554.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-23 14:43:51

Index(['ONU external ID', 'PON Type', 'SN', 'Onu Type', 'Name', 'OLT', 'Board',
       'Port', 'Estado', 'Estatus', 'Allocated ONU', 'Zone', 'Address',
       'Latitude', 'Longitude', 'ODB (Splitter)', 'ODB Port', 'Mode',
       'WAN mode', 'IP address', 'Subnet mask', 'Default gateway', 'DNS1',
       'DNS2', 'Username', 'Password', 'CATV', 'Administrative status',
       'Auth date', 'Status', 'Signal', 'Signal 1310', 'Signal 1490',
       'Distance(m)', 'Service port', 'Service port VLAN',
       'Service port CVLAN', 'Service port SVLAN',
       'Service port tag transform mode', 'Service port upload speed',
       'Service port download speed', 'Contact', 'TR069 Profile',
       'TR069 Device ID', 'Last status change'],
      dtype='object')

,N° Abonado,Documento,Cliente,Estatus_x,Fecha,Hora,Tipo Llamada,Tipo Respuesta,Detalle Respuesta,Vendedor,...,Service port VLAN,Service port CVLAN,Service port SVLAN,Service port tag transform mode,Service port upload speed,Service port download speed,Contact,TR069 Profile,TR069 Device ID,Last status change
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2404.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-07 11:55:30
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-16 13:11:38
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-15 12:12:39
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,38.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-21 09:40:38
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2404.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-02 10:24:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,11.0,translate,FTTH_200,FTTH_200,NaN,NaN,NaN,2026-04-15 09:37:57
1683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,6.0,translate,FTTH_250,FTTH_250,NaN,NaN,NaN,2026-04-16 10:34:16
1719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,2239.0,translate,FTTH_600,FTTH_600,NaN,NaN,NaN,2026-04-20 10:30:22
1743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,59.0,translate,PYME_60,PYME_60,NaN,NaN,NaN,2026-04-19 20:03:16
1747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,NaN,3.0,translate,FTTH_500,FTTH_500,NaN,NaN,NaN,2026-04-20 12:54:43

In [36]:
import pandas as pd

# 1. Carga de datos
df_ONT = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\ONT_OFF_Gold.parquet')
df_ONT.to_excel(r'C:\Users\josperez\Downloads\ONT_OFF_Gold.xlsx', index=False)