Objetivo: Probar la lógica de limpieza de tiempos negativos y validación de outliers usando .mask() antes de pasarlo al script maestro.
Autor: José Arturo Pérez Falcón
Fecha: Febrero 2026

In [16]:
import pandas as pd

df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Silver_PBI_Final.parquet')
df.info()
print(df.describe())
display(df)

""" # 1. Le decimos a Pandas que repita cada fila el número de veces que diga 'Total_Ordenes'
# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente
df_prueba = df.loc[df.index.repeat(df['Total_Ordenes'])]

# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación
display(df_prueba.groupby('Clasificacion')['SLA Resolucion Min'].median())
display(df) """

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133197 entries, 0 to 133196
Data columns (total 6 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   N° Orden            133197 non-null  object
 1   Quincena Evaluada   133197 non-null  object
 2   Franquicia          133197 non-null  object
 3   Clasificacion       133197 non-null  object
 4   SLA Resolucion Min  133197 non-null  float64
 5   SLA_Bin             133197 non-null  float64
dtypes: float64(2), object(4)
memory usage: 6.1+ MB
       SLA Resolucion Min        SLA_Bin
count       133197.000000  133197.000000
mean          1355.432149    1351.047899
std           3152.603756    3152.534176
min              1.000000       1.000000
25%             83.000000      80.000000
50%            194.000000     190.000000
75%           1526.000000    1520.000000
max          65035.000000   65030.000000

,N° Orden,Quincena Evaluada,Franquicia,Clasificacion,SLA Resolucion Min,SLA_Bin
0,V120861,AGO 2025 Q1,FIBEX VALENCIA,NOC,36.0,30.0
1,VC112838,AGO 2025 Q1,FIBEX VILLA DE CURA,NOC,50.0,50.0
2,GU118214,AGO 2025 Q1,FIBEX GUARICO,NOC,22.0,20.0
3,C114940,AGO 2025 Q1,FIBEX CARACAS,MESA DE CONTROL,1.0,1.0
4,V134699,AGO 2025 Q1,FIBEX VALENCIA,MESA DE CONTROL,5522.0,5520.0
...,...,...,...,...,...,...
133192,MAR168126,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,7570.0,7570.0
133193,MAR171435,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,5052.0,5050.0
133194,MAR168139,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,6788.0,6780.0
133195,LCH339531,FEB 2026 Q1,FIBEX ANZOATEGUI,MESA DE CONTROL,19.0,10.0
133196,MAR173453,FEB 2026 Q1,FIBEX MARIARA,MESA DE CONTROL,16.0,10.0

' # 1. Le decimos a Pandas que repita cada fila el número de veces que diga \'Total_Ordenes\'\n# Esto "descomprime" la tabla de frecuencias de vuelta a la Capa Silver virtualmente\ndf_prueba = df.loc[df.index.repeat(df[\'Total_Ordenes\'])]\n\n# 2. Ahora sí, le pedimos la mediana real agrupada por Clasificación\ndisplay(df_prueba.groupby(\'Clasificacion\')[\'SLA Resolucion Min\'].median())\ndisplay(df) '

In [17]:
import pandas as pd
df = pd.read_parquet(r'C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\silver_data\Tickets_Silver_Master.parquet')

display(df)

,Quincena Evaluada,FechaInicio,FechaFin,Fecha Apertura,Fecha Impresion,Fecha Cierre,Fecha Apertura Date,Fecha Cierre Date,Es_Falla,Cumplio_SLA,...,N° Contrato,N° Orden,Estatus contrato,Estatus_orden,Usuario Final,Usuario Emisión,Usuario Impresión,Solucion Aplicada,Detalle Orden,SLA Detalle Texto
0,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-01 15:47:00,2026-02-01 16:08:00,NaT,2026-02-01,NaT,1,0,...,LCH36432,LCH266825,ACTIVO,IMPRESA,None,APICONEXVE,FLEAL,None,NO NAVEGA EN CIERTAS PAGINAS,None
1,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02 07:55:00,2026-02-02 07:55:00,NaT,2026-02-02,NaT,1,0,...,MB0280,MB5761,ACTIVO,IMPRESA,None,RYZORRILLA,RYZORRILLA,None,CAIDAS SEGUIDAS DE INTERNET,None
2,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02 08:26:00,2026-02-02 08:27:00,NaT,2026-02-02,NaT,1,0,...,MB1385,MB5762,ACTIVO,IMPRESA,None,RYZORRILLA,RYZORRILLA,None,FALLA LOS,None
3,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02 08:53:00,2026-02-02 08:53:00,NaT,2026-02-02,NaT,1,0,...,POR1000,POR6526,ACTIVO,IMPRESA,None,YOMARTINEZ,YOMARTINEZ,None,FALLA LOS,None
4,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-02 08:35:00,2026-02-02 08:35:00,NaT,2026-02-02,NaT,1,0,...,MB1484,MB5764,ACTIVO,IMPRESA,None,JOTARAZONA,JOTARAZONA,None,CAIDAS SEGUIDAS DE INTERNET,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137684,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-10 17:37:00,2026-02-10 18:55:00,2026-02-15 23:47:00,2026-02-10,2026-02-15,1,0,...,6592-03-01 00:00:00,MAR168126,ACTIVO,FINALIZADA,ANQUINTERO,APICONEXVE,LJVILLEGAS,FALLA GENERAL,SIN INTERNET,5 days 06:10:00
137685,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-12 11:36:00,2026-02-12 11:37:00,2026-02-15 23:48:00,2026-02-12,2026-02-15,1,0,...,6270-03-01 00:00:00,MAR171435,ACTIVO,FINALIZADA,ANQUINTERO,CALOPEZ,CALOPEZ,FALLA GENERAL,FALLA LOS,3 days 12:12:00
137686,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-11 06:44:00,2026-02-11 06:44:00,2026-02-15 23:52:00,2026-02-11,2026-02-15,1,0,...,5340-03-01 00:00:00,MAR168139,ACTIVO,FINALIZADA,ANQUINTERO,MARIPEREZ,MARIPEREZ,FALLA GENERAL,FALLA LOS,4 days 17:08:00
137687,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-15 23:34:00,2026-02-15 23:47:00,2026-02-15 23:53:00,2026-02-15,2026-02-15,1,1,...,LCH70020,LCH339531,ACTIVO,FINALIZADA,WILLMARTINEZ,APICONEXVE,WILLMARTINEZ,CAMBIO DE VLAN,INTERNET LENTO,0 days 00:19:00
137688,FEB 2026 Q1,2026-01-01,2026-02-15,2026-02-15 23:41:00,2026-02-15 23:53:00,2026-02-15 23:57:00,2026-02-15,2026-02-15,1,1,...,6733-03-01 00:00:00,MAR173453,ACTIVO,FINALIZADA,WILLMARTINEZ,APICONEXVE,WILLMARTINEZ,REINICIAR EQUIPO,INTERNET LENTO,0 days 00:16:00