Pagos Virtuales

In [26]:
import pandas as pd
import numpy as np

ruta = r"C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\raw_data\1-Recaudación\3-Pago virtual\Data-Recaudacion Virtual 01-04-2026 al 14-04-2026.xlsx"
df = pd.read_excel(ruta, engine="calamine")

display(df.describe(include="all"))
display(df.dtypes)
display(df.columns)
display(df['Usuario'].value_counts())
df['Categoria'] = np.where(df['Usuario'] == 'APICONEXVE', 'App', 'Manual')
cols = ['N° Abonado', 'Fecha','Forma de Pago','Usuario', 'Oficina Cobro', 'Categoria']
df = df[cols]
display(df.info())

df_group = df.groupby(['Usuario', 'Fecha', 'Forma de Pago','Oficina Cobro']).agg(cantidad=('N° Abonado', 'size')).reset_index()
display(df_group)
mask_oficina = df['Oficina Cobro'].str.contains('VIRTUAL')
mask_usuario = df['Usuario'] == 'APICONEXVE'

display(df[mask_usuario].groupby(['Oficina Cobro', 'Usuario', 'Forma de Pago']).agg(cantidad=('N° Abonado', 'size')).reset_index())
display(df[mask_oficina].groupby(['Oficina Cobro', 'Usuario', 'Forma de Pago']).agg(cantidad=('N° Abonado', 'size')).reset_index())
display(df[mask_oficina].groupby(['Categoria']).agg(cantidad=('N° Abonado', 'size')).reset_index())

,ID Contrato,ID Pago,N° Abonado,Documento,Fecha,Estatus Pago,Forma de Pago,Banco,Cobrador,Usuario,Oficina Cobro,Ciudad
count,259103,259103,259103,2.591030e+05,259103,259103,259103,259054,259103,259103,259103,259103
unique,221719,259103,221582,NaN,NaN,1,6,14,12,516,21,120
top,'CONT02368D40E6F05750','69DE8C539D6D10557026',A70788,NaN,NaN,PAGADO,DEPOSITO BS,BANCO MERCANTIL,COBRADOR VIRTUAL,APICONEXVE,OFI-VIRTUAL,VALENCIA
freq,231,1,231,NaN,NaN,259103,194559,131585,215537,148507,203738,59280
mean,NaN,NaN,NaN,2.875389e+07,2026-04-08 16:30:20.903656192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.637000e+01,2026-04-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.310493e+07,2026-04-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.804462e+07,2026-04-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.474240e+07,2026-04-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,9.509195e+10,2026-04-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,3.523154e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ID Contrato              object
ID Pago                  object
N° Abonado               object
Documento               float64
Fecha            datetime64[ns]
Estatus Pago             object
Forma de Pago            object
Banco                    object
Cobrador                 object
Usuario                  object
Oficina Cobro            object
Ciudad                   object
dtype: object

Index(['ID Contrato', 'ID Pago', 'N° Abonado', 'Documento', 'Fecha',
       'Estatus Pago', 'Forma de Pago', 'Banco', 'Cobrador', 'Usuario',
       'Oficina Cobro', 'Ciudad'],
      dtype='object')

Usuario
APICONEXVE    148507
MESCALONA      15314
AGUILARY       12871
MARTINEZE      10757
GARCIACA        4560
               ...
LIHERRERA          1
KSILVA             1
MGARCIAS           1
KGIMENEZ           1
BOADA              1
Name: count, Length: 516, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259103 entries, 0 to 259102
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   N° Abonado     259103 non-null  object
 1   Fecha          259103 non-null  datetime64[ns]
 2   Forma de Pago  259103 non-null  object
 3   Usuario        259103 non-null  object
 4   Oficina Cobro  259103 non-null  object
 5   Categoria      259103 non-null  object
dtypes: datetime64[ns](1), object(5)
memory usage: 11.9+ MB

None

      Usuario      Fecha Forma de Pago Oficina Cobro  cantidad
0     AACAMPO 2026-04-07   DEPOSITO BS   OFI-VIRTUAL         1
1     AACAMPO 2026-04-08   DEPOSITO BS   OFI-VIRTUAL         3
2     AACAMPO 2026-04-09   DEPOSITO BS   OFI-VIRTUAL         2
3     AACAMPO 2026-04-10   DEPOSITO BS   OFI-VIRTUAL         6
4     AACAMPO 2026-04-11   DEPOSITO BS   OFI-VIRTUAL         3
...       ...        ...           ...           ...       ...
7518   ZRIVAS 2026-04-09    PAGO MOVIL   OFI-VIRTUAL         3
7519   ZRIVAS 2026-04-10   DEPOSITO BS   OFI-VIRTUAL         1
7520   ZRIVAS 2026-04-10    PAGO MOVIL   OFI-VIRTUAL         7
7521   ZRIVAS 2026-04-13    PAGO MOVIL   OFI-VIRTUAL         7
7522   ZRIVAS 2026-04-14    PAGO MOVIL   OFI-VIRTUAL         3

[7523 rows x 5 columns]

                          Oficina Cobro     Usuario    Forma de Pago  cantidad
0               OFC - LAGUNITAS VIRTUAL  APICONEXVE      DEPOSITO BS       113
1           OFC - PUNTA DE MATA VIRTUAL  APICONEXVE      DEPOSITO BS       180
2   OFC - SAN FERNANDO DE APURE VIRTUAL  APICONEXVE      DEPOSITO BS      1883
3   OFC - SAN FERNANDO DE APURE VIRTUAL  APICONEXVE  DEPOSITO DOLLAR        28
4                  OFC - VIRTUAL ARAGUA  APICONEXVE      DEPOSITO BS     12770
5                  OFC - VIRTUAL ARAGUA  APICONEXVE  DEPOSITO DOLLAR        15
6                 OFC - VIRTUAL BARINAS  APICONEXVE      DEPOSITO BS       494
7                   OFC - VIRTUAL BELEN  APICONEXVE      DEPOSITO BS        65
8                  OFC - VIRTUAL GUIGUE  APICONEXVE      DEPOSITO BS       805
9               OFC - VIRTUAL LA GUAIRA  APICONEXVE      DEPOSITO BS      2665
10              OFC - VIRTUAL LA GUAIRA  APICONEXVE  DEPOSITO DOLLAR         3
11              OFC - VIRTUAL LA PUENTE  APICONEXVE      DEPOSITO BS         3
12        OFC VIRTUAL - FIBEX MAGDALENO  APICONEXVE      DEPOSITO BS        41
13          OFC VIRTUAL- FIBEX CAUCAGUA  APICONEXVE      DEPOSITO BS        11
14                          OFC-VIRTUAL  APICONEXVE      DEPOSITO BS      1352
15                          OFC-VIRTUAL  APICONEXVE  DEPOSITO DOLLAR         1
16           OFC-VIRTUAL ARAGUA MATURIN  APICONEXVE      DEPOSITO BS        70
17           OFC-VIRTUAL ARAGUA MATURIN  APICONEXVE  DEPOSITO DOLLAR         1
18                       OFC-VIRTUAL FH  APICONEXVE      DEPOSITO BS       776
19                 OFC-VIRTUAL LA SILSA  APICONEXVE      DEPOSITO BS       108
20               OFC-VIRTUAL LA TOSCANA  APICONEXVE      DEPOSITO BS       212
21             OFC-VIRTUAL LAS ADJUNTAS  APICONEXVE      DEPOSITO BS      1795
22             OFC-VIRTUAL LAS ADJUNTAS  APICONEXVE  DEPOSITO DOLLAR         1
23                    OFC-VIRTUAL YAGUA  APICONEXVE      DEPOSITO BS       516
24                          OFI-VIRTUAL  APICONEXVE      DEPOSITO BS    124265
25                          OFI-VIRTUAL  APICONEXVE  DEPOSITO DOLLAR       148
26             ORC - PORTUGUESA VIRTUAL  APICONEXVE      DEPOSITO BS       186

                 Oficina Cobro     Usuario     Forma de Pago  cantidad
0      OFC - LAGUNITAS VIRTUAL    AGUILARY       DEPOSITO BS         2
1      OFC - LAGUNITAS VIRTUAL    AGUILARY        PAGO MOVIL        10
2      OFC - LAGUNITAS VIRTUAL    ALONDONO        PAGO MOVIL         2
3      OFC - LAGUNITAS VIRTUAL  APICONEXVE       DEPOSITO BS       113
4      OFC - LAGUNITAS VIRTUAL     EJORTIZ       DEPOSITO BS         1
...                        ...         ...               ...       ...
1801  ORC - PORTUGUESA VIRTUAL      SBENAL       DEPOSITO BS         4
1802  ORC - PORTUGUESA VIRTUAL      SBENAL        PAGO MOVIL         3
1803  ORC - PORTUGUESA VIRTUAL       VLEON        PAGO MOVIL        10
1804  ORC - PORTUGUESA VIRTUAL  YOMARTINEZ        PAGO MOVIL       129
1805  ORC - PORTUGUESA VIRTUAL  YOMARTINEZ  TRANSFERENCIA BS         1

[1806 rows x 4 columns]

  Categoria  cantidad
0       App    148507
1    Manual    110596