In [2]:
import pandas as pd

df = pd.read_parquet(r"c:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\UAbonados_Gold.parquet")
display(df)

,ID,N° Abonado,Documento,Cliente,Fecha Contrato,Estatus,Nombre Franquicia,Source.Name
0,'CONTFF7002ACCEC43838',T1965,31281196,MAIKER JOSE LOPEZ MENDOZA,2023-09-11 00:00:00,ACTIVO,FIBEX TINAQUILLO,Data-Costumers05022026.xlsx
1,'CONTB76FA1259AF06471',V97202,13956779,NELSON FIDEL ESCALONA OLIVEROS,2025-02-20 00:00:00,ACTIVO,FIBEX VALENCIA,Data-Costumers05022026.xlsx
2,'CONTFFE753225FA48013',C28264,23634391,NAYLIT MERCEDES MONTES FUENMAYOR,2024-10-04 00:00:00,ACTIVO,FIBEX CARACAS,Data-Costumers05022026.xlsx
3,'CONTC7B204366AF12595',MAR0100,20243186,YURIMAR NAZARETH DELGADO IZQUIERDO,2024-02-10 00:00:00,ACTIVO,FIBEX MARIARA,Data-Costumers05022026.xlsx
4,'CONTA517B6F009923500',T8427,16773921,ALVENIS MIGUEL RUIZ BARRIOS,2025-02-06 00:00:00,ACTIVO,FIBEX TINAQUILLO,Data-Costumers05022026.xlsx
...,...,...,...,...,...,...,...,...
686505,'CONTF4539E8AFF649014',MI6571,27037288,MIZRAIM ORTIZ TOVAR,2025-04-07 00:00:00,ACTIVO,FIBEX MIRANDA,Data-Costumers05022026.xlsx
686506,'CONTF453BC5C7E253028',SR1486,20268910,ANTONY JOSE MATUTE ESCALONA,2024-03-15 00:00:00,ACTIVO,FIBEX SAN RAFAEL,Data-Costumers05022026.xlsx
686507,'CONTF453EC5A25E04910',C27709,19399461,RAFAEL LEONARDO GONZáLEZ GARCíA,2024-09-25 00:00:00,ACTIVO,FIBEX CARACAS,Data-Costumers05022026.xlsx
686508,'CONTF4540E6BAFC74992',LG20077,19593330,BARBARA MICHELENA BRICEÑO,2024-03-15 00:00:00,POR RETIRAR,FIBEX LA GUAIRA,Data-Costumers05022026.xlsx
686509,'CONTF4542AE7A3865340',V1690,7103110,LUIS ENRIQUE MENDOZA MIRELES,2022-01-28 00:00:00,ACTIVO,FIBEX VALENCIA,Data-Costumers05022026.xlsx

In [3]:
df2 = pd.read_parquet(r"C:\Users\josperez\Documents\A-DataStack\01-Proyectos\01-Data_PipelinesFibex\02_Data_Lake\gold_data\Dim_Cliente.parquet")
display(df2)

,Cliente_SK,ID,Cliente,Fecha Contrato,Estatus,Suscripción,Grupo Afinidad,Nombre Franquicia,Ciudad,Vendedor,Serv/Paquete,Documento,N° Abonado
0,1,'CONT70DBA2F009C33647',LENDYS YOHARY CAMPOS LOPEZ,2023-12-06,ACTIVO,25.00,HOGAR,FIBEX SAN CARLOS,SAN CARLOS,JESUS ARCANGEL NIEVES HERNANDEZ VENTAS CALLE ...,FTTH_50,None,SC7969
1,2,'CONT71B2C8A830782206',JOSE EDUARDO ARRAIZ LOPEZ,2023-12-07,CORTADO,25.00,HOGAR,FIBEX SAN CARLOS,SAN CARLOS,HENRRY JOHAN FERNANDEZ VENTAS CALLE SAN CARLOS,FTTH_50,None,SC7978
2,3,'CONT3054B0A13FC36757',ALEJANDRA DEL CARMEN NÚÑEZ JIMÉNEZ,2025-05-23,ACTIVO,32.00,HOGAR,FIBEX ANZOATEGUI,ANACO,JOSE ESTEBAN ORTIZ MENDOZA,FTTH_600,None,LCH59798
3,4,'CONT3EDE9BEC8DA31581',GENY DAZA,2022-10-06,ACTIVO,42.00,HOGAR,FIBEX VALENCIA,VALENCIA,KEYLIN REBOLLEDO TELEVENTAS,FTTH_500,None,V15041
4,5,'CONT87183D9F88B52696',MARIA VALENTINA MEALHA SOUSA,2021-04-26,ANULADO,40.00,HOGAR,FIBEX VALENCIA,VALENCIA,CARMEN JUSNEIDY MARTINEZ VARON,None,None,H4781
...,...,...,...,...,...,...,...,...,...,...,...,...,...
716166,730187,'CONTF60C769763771713',HESNOL RAMON ROSENDO OCHOA,2026-05-02,POR INSTALAR,29.00,HOGAR,FIBEX VALENCIA,CAMPO CARABOBO,AGENTE AUTORIZADO IG TECNOLOGY JUNAISY FERNANDEZ,None,None,V142120
716167,730188,'CONTF61A747E03548744',SIMON ALBERTO CABALLERO BELLO,2026-05-02,POR INSTALAR,52.20,HOGAR,FIBEX VALENCIA,VALENCIA,GENESIS REBOLLEDO OFIC TORRE FIBEX VIñEDO,FTTH_300,None,V142132
716168,730189,'CONTF627EA8C8CB31666',AQUILES RODOLFO VERA HERNANDEZ,2026-05-02,POR INSTALAR,46.40,HOGAR,FIBEX VALENCIA,VALENCIA,KATIUSKA DANIELA C MENDEZ OFI SAMBIL VALENCIA,None,None,V142141
716169,730190,'CONTF63EAF3D9A749696',YASMIRA JOSEFINA SáNCHEZ ALVAREZ,2026-05-02,ACTIVO,29.00,HOGAR,FIBEX VALENCIA,VALENCIA,JENNITSANCHEZ AGENTE AUTORIZADO INTERALMAR,FTTH_400,None,V142152
716170,730191,'CONTF673DAE5AFE96506',YHOSELY ANGELICA GARCIA VILLAMEDIANA,2026-05-02,SIN FACTIBILIDAD,29.00,HOGAR,FIBEX VALENCIA,CAMPO CARABOBO,AGENTE AUTORIZADO IG TECNOLOGY JUNAISY FERNANDEZ,None,None,V142169